[theme]
base="dark"

# Mesma cor primária laranja
primaryColor="#FF8C00"

# Cor de fundo bem escura
backgroundColor="#000000"

# Fundo secundário (sidebar) ligeiramente mais claro
secondaryBackgroundColor="#333333"

# Cor do texto (branca)
textColor="#FFFFFF"

# Fonte
font="serif"
