[theme]
# Cores primárias
primaryColor = "#00774D"  # Verde Tracky para botões e elementos interativos
backgroundColor = "#EBF3EF"  # Fundo geral muito claro
secondaryBackgroundColor = "#ffffff"  # Fundo de cards e containers
textColor = "#333333"  # Cor do texto principal

# Fonte
font = "sans-serif"

[server]
enableStaticServing = true

[browser]
gatherUsageStats = false

[global]
showWarningOnDirectExecution = false